### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by capnkenny** [novelrt/novelrt.github.io#13]
Currently we have the Gatsby Minimal Starter readme - we just want to update this to represent the NovelRT Website, and how to get started with running it locally... which is _pretty close_, we're just not making a new project 😄

**Comment by cynthiateeters** [comment]
I'd like to work on this. Please assign it to me.

**Comment by capnkenny** [comment]
Assigned - let @RubyNova or myself know if you need anything 🙂

**Comment by cynthiateeters** [comment]
Thanks.
One question: When you say, " how to get started with running it locally" I assume you mean the NovelRT app and not Gatsby. 

So I should look at the README at https://github.com/novelrt/NovelRT for that info?

**Comment by capnkenny** [comment]
Good question! For this issue, I'm actually meaning how to run the website locally to test/develop with - not the NovelRT engine itself (we'll keep that in the engine's repo for now)

**Comment by cynthiateeters** [comment]
Excellent news for me. I'm more familiar with Gatsby.

**Comment by capnkenny** [comment]
Ticket has been resolved - closing.
