### ISSUE TITLE
Take out duplicated SVG from index

### ISSUE THREAD

**Issue by cynthiateeters** [novelrt/novelrt.github.io#29]
For the secondary branding on the main page, 

- change the layout of those 2 divs from flex to grid
- remove duplicated SVG
- have first icon to the left of the text
- use col-start to swap second icon so that it the right of the text

**Please consider putting Hacktoberfest label on this issue**

**Comment by TraceLD** [comment]
> this is a goodfirstissue?
If you're good at TailwindCSS, yes

**Comment by cynthiateeters** [comment]
Please assign this to me.
