### ISSUE TITLE
Design and add new favicon

### ISSUE THREAD

**Issue by cynthiateeters** [novelrt/novelrt.github.io#35]
The site could use its own favicon.

If this is accepted, please assign it to emgrey02

**Comment by TraceLD** [comment]
> I was hoping to give it to Emma Grey (emgrey02) for a Hacktoberfest win.
I was just typing out a comment saying I missed that bit of your original message. I'll assign it to them :)

**Comment by cynthiateeters** [comment]
@emgrey02  - it looks like the issue is yours if you want it.
