### ISSUE TITLE
Redirecting documentation link to Doxygen

### ISSUE THREAD

**Issue by capnkenny** [novelrt/novelrt.github.io#4]
Currently, we are generating HTML documentation with Doxygen as part of the Engine. With that said, we will want to make `/docs` redirect to the `https://novelrt.github.io/NovelRT/` page from the engine repo to allow an easy way to get to the Doxygen documentation.

_Edited to represent earlier design choice made_

**Comment by capnkenny** [comment]
CC @TraceLD / @FiniteReality (just in case you have any ideas around Doxy)

**Comment by FiniteReality** [comment]
If we push to the gh-pages branch in NovelRT/NovelRT we could have the docs stored in the NovelRT repo.

**Comment by capnkenny** [comment]
Still working on this - using gh-pages branch of NovelRT/NovelRT to host the doxygen pages.

**Comment by capnkenny** [comment]
Doxygen docs have now been published, so this should now work :)
