### ISSUE TITLE
Add list of current contributors to Contribution page

### ISSUE THREAD

**Issue by capnkenny** [novelrt/novelrt.github.io#7]
If possible, we can use the GitHub API to pull the list of contributors per project and try to display them on page.

Not sure if we want to hand-code this ourselves or to use a module of sorts to pull the info from the API.

**Comment by capnkenny** [comment]
https://www.gatsbyjs.com/plugins/gatsby-source-github/

Something to look into

**Comment by TraceLD** [comment]
I'll take this one 😄
